services:
  rabbitmq-demo:
    image: rabbitmq:3-management
    environment:
      - TCP_PORTS=15672, 5672
    ports:
      - 15672:15672
      - 5672:5672
  cassandra1:
    image: cassandra:4.0
    container_name: cassandra1
    hostname: cassandra1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=SolarSystem
    entrypoint: ["chmod", "+x", "/sample_data.sh"]
    volumes:
      - ./sample_data.sh:/sample_data.sh