name: Maven Run Tests when push to Main branch and newly created PRs.

on:
  # Trigger the workflow on pull request for main branch
  # and for subsequent commits pushed to this PR.
  push:
    pull_request:
      branches:
        - main
      types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml