on:
  # Trigger the workflow on pull request for main branch
  # and for subsequent commits pushed to this PR.
  push:
    pull_request:
      branches:
        - main
      types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
  unittest:
    name: Maven Run Tests when push to Main branch and newly created PRs.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
  sonarcloud:
    name: SonarQube run when push to Main branch and newly created PRs.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Analyze with SonarCloud
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        #run: mvn -B verify sonar:sonar -Dsonar.projectKey=brocube -Dsonar.organization=gaugerard -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}